### ISSUE TITLE
Buffer is buggy on Chrome, because Chrome became stricter 

### ISSUE THREAD

**Issue by JSteunou** [mistadikay/strict-loader#5] opened 2015-12-15 16:48 UTC
This loader do not work with Chrome anymore

I dont know if the solution should come from you or webpack itself

see https://github.com/feross/buffer/issues/79

**Comment by mistadikay** [comment] 2015-12-16 03:33
@JSteunou Hi. Thanks for the catch, but could you tell me please how can I reproduce it?

**Comment by JSteunou** [comment] 2015-12-16 07:49
I reproduce it any time I'm using this loader with webpack-dev-server and Chromium / Chrome 47

**Comment by mistadikay** [comment] 2015-12-16 08:49
@JSteunou can you run [this demo](https://github.com/mistadikay/strict-loader#demo) and see if it's reproducible there? I couldn't see any errors regarding Buffer (`Chrome 48.0.2564.41 beta (64-bit)`)

**Comment by JSteunou** [comment] 2015-12-16 09:00
It works (after removing fat arrows in your code :p). In your demo Buffer is never called whereas in my projects + strict-loader it is called inside browser and that lines make Chrome >= 45 unhappy

``` js
// pre-set for values that may exist in the future
Buffer.prototype.length = undefined
Buffer.prototype.parent = undefined
```

**Comment by mistadikay** [comment] 2015-12-16 09:14
@JSteunou oops, I got used to ES6 already :smiley: Okay, from what I see: since all I do in this simple loader is just use standard webpack API, I don't think this problem is a problem of a particular loader — it's either `buffer` itself or the way webpack uses it. Closing.

**Closed as completed by mistadikay** 2015-12-16 09:14 UTC
Labels: wontfix

**Comment by JSteunou** [comment] 2015-12-16 09:24
Agree, I run the Buffer test suit and nothing pops so I'm starting to think webpack does weird thing with it.

**Comment by JSteunou** [comment] 2015-12-16 09:26
One last question: is using `require('webpack/lib/OriginalSource');`  a common thing for a loader?

**Comment by JSteunou** [comment] 2015-12-16 09:45
Hooooo find it!! I exclude `node_modules` for this loader! strict mode on the Buffer lib prevent from write on prototype because Buffer already exists in Chrome!

For the people that will use your loader, I strongly advice to use [loader include / exclude](https://webpack.github.io/docs/configuration.html#module-loaders) configuration.

**Comment by mistadikay** [comment] 2015-12-16 10:20
> One last question: is using require('webpack/lib/OriginalSource'); a common thing for a loader?

@JSteunou You're right, created an issue #6

**Comment by JSteunou** [comment] 2015-12-24 21:01
fixed on Buffer, on next release all should be ok https://github.com/feross/buffer/issues/79#issuecomment-167044636

**Comment by mistadikay** [comment] 2015-12-25 07:08
@JSteunou thanks for the heads up!
